import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import Providers from "./providers";
import { ThemeApplier } from "@components/providers/ThemeApplier";
import FarcasterBoot from "./farcaster-boot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const initTheme = `
(function () {
  try {
    var raw = localStorage.getItem("cryptonaire-ui");
    if (!raw) return;
    var data = JSON.parse(raw);
    var theme = (data && data.state && data.state.theme) || "light";
    var cls = document.documentElement.classList;
    if (theme === "dark") cls.add("dark"); else cls.remove("dark");
  } catch (e) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={jakarta.variable}>
      <head>
        <script dangerouslySetInnerHTML={{ __html: initTheme }} />
      </head>
      <body
        className={`min-h-dvh bg-background text-ink-900 font-sans antialiased`}
      >
        <Providers>
          <ThemeApplier />
          <FarcasterBoot/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
